# Generated by Django 5.2.17 on 2026-09-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Booking Requested'), ('ACCEPTED', 'Provider Accepted'), ('ON_THE_WAY', 'Provider On The Way'), ('ARRIVED', 'Provider Arrived'), ('IN_PROGRESS', 'Service In Progress'), ('COMPLETED', 'Service Completed'), ('RATING_PENDING', 'Rating & Review Pending'), ('CLOSED', 'Completed & Closed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=25),
        ),
    ]
