# Generated by Django 5.2.17 on 2026-08-16 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(blank=True, default='', max_length=200)),
                ('certificate_file', models.FileField(upload_to='certificates/')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Certificate',
                'verbose_name_plural': 'Provider Certificates',
                'db_table': 'vega_provider_certificates',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
