# Generated by Django 5.2.17 on 2026-09-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_providercertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Uploaded user/provider profile photo', null=True, upload_to='profile_photos/'),
        ),
    ]
