# Generated by Django 5.2.17 on 2026-09-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='reset_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='otp',
            field=models.CharField(max_length=128),
        ),
    ]
